---
title: "Shuffle Analysis"
author: "Daniel Morán Jiménez"
date: "7/20/2018"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

library(dplyr)
library(tidyr)
library(ggplot2)
```

## Basic experiments on Magic Decks

The first experiment will consist on generating decks with one two and three colors, and get a first taste of how often a hand is really bad. To this extent, we generate the three decks and shuffle them using a random shuffle, and then draw 1000 hands from the decks, shuffling each time we draw a hand.

```{r}
source('./decks.R')

nHands <- 2000

decks <- list(deck1 = generateDeck(c(1), 10:19),
              deck2 = generateDeck(1:2, c(10:14, 20:24)),
              deck3 = generateDeck(1:3, c(10:12, 20:22, 30:33)))

shuffles <- list(random = shuffleRandom,
                 randomCuts = simpleRandomCuts(),
                 randomPrepaired = prepareShuffle(shuffleRandom),
                 randomCutsPrepaired = prepareShuffle(simpleRandomCuts()))

globalHands <- data.frame()

for (name in names(decks)) {
  for (shuffleName in names(shuffles)) {
    hands <- analyzeHands(drawNHands(decks[[name]], nHands, shuffleFn=shuffles[[shuffleName]]))
    hands$deck <- name
    hands$shuffle <- shuffleName
    
    globalHands <- rbind(globalHands, hands)
  }
}

```


```{r, fig.height=8, fig.width=10}
globalHands %>%
  gather(feature, value, -deck, -shuffle) %>%
  ggplot(aes(x = value, group = shuffle, fill = shuffle)) +
    geom_bar(stat="count", position="dodge", color = "black") +
    facet_grid(feature ~ deck, scales="free")
```
